# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Mark Gurianov
title: Junior Java developer
email: mark1708.work@gmail.com
phone: +7(962)024-50-04


# Social links
# twitter_username: facespics
github_username:  Mark1708
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: mark-gurianov-605616201
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: "Telegram"
    icon: "telegram"
    url: "https://t.me/MarkStav"
  - title: "Vk"
    icon: "vk"
    url: "https://vk.com/mgurianov"



# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Mark and I'm a backend Java developer. Currently I am studying at ITMO in the direction of Neurotechnology and Programming and at Skillbox in the course “Profession of Java developer PRO”.
  At the moment, there are already many skills that I would like to try in the work area.

  I am most skilled in: <mark>Java</mark>, <mark>Spring</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Crossfit
#   - Gaming
#   - Knitting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

darkmode: true
